// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: src/main/java/de/dhbw/compiler/xparser/JFlexXScanner.lex

/* **********************************************
 * Duale Hochschule Baden-Württemberg Karlsruhe
 * Prof. Dr. Jörn Eisenbiegler
 * 
 * Vorlesung Übersetzerbau
 * Praxis X Abstiegsparser
 * - Scanner-Definition
 * 
 * **********************************************
 */


package de.dhbw.compiler.LL1Parser;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public final class JFlexXScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int INT = 2;
  public static final int FRACTION = 4;
  public static final int EXPVZ = 6;
  public static final int EXP = 8;
  public static final int STRING = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\3\1\1\0\2\1\22\0\1\2\1\0\1\3"+
    "\5\0\1\4\1\5\1\6\1\7\1\0\1\10\1\11"+
    "\1\12\1\13\11\14\1\15\1\16\1\17\1\20\1\21"+
    "\2\0\4\22\1\23\25\22\1\0\1\24\4\0\1\25"+
    "\1\26\1\22\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\2\22\1\35\1\36\1\37\1\40\1\41\1\22\1\42"+
    "\1\43\1\44\2\22\1\45\3\22\u0185\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\12\22\1\23\1\24\1\25\1\23\1\26"+
    "\1\27\1\26\2\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\35\1\0\1\40\1\41\5\22\1\42"+
    "\6\22\1\0\1\43\1\0\1\44\1\45\1\46\1\0"+
    "\2\22\1\47\1\22\1\50\1\51\6\22\1\52\1\22"+
    "\1\53\3\22\1\54\1\22\1\55\1\22\1\56\1\57"+
    "\1\60\2\22\1\61\1\22\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\344\0\344\0\344\0\344\0\344\0\344\0\344\0\u0130"+
    "\0\u0156\0\344\0\u017c\0\344\0\344\0\344\0\344\0\u01a2"+
    "\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2"+
    "\0\u02f8\0\344\0\344\0\344\0\u031e\0\344\0\344\0\u0344"+
    "\0\344\0\u036a\0\344\0\344\0\344\0\344\0\344\0\344"+
    "\0\344\0\u0390\0\u03b6\0\344\0\344\0\u03dc\0\u0402\0\u0428"+
    "\0\u044e\0\u0474\0\u01a2\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532"+
    "\0\u0558\0\u057e\0\344\0\u05a4\0\344\0\344\0\344\0\u05ca"+
    "\0\u05f0\0\u0616\0\u01a2\0\u063c\0\u01a2\0\u01a2\0\u0662\0\u0688"+
    "\0\u06ae\0\u06d4\0\u06fa\0\u0720\0\344\0\u0746\0\u01a2\0\u076c"+
    "\0\u0792\0\u07b8\0\u01a2\0\u07de\0\u01a2\0\u0804\0\u01a2\0\u01a2"+
    "\0\u01a2\0\u082a\0\u0850\0\u01a2\0\u0876\0\u01a2\0\u01a2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\2\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\30\1\7\1\30\1\31\1\30\1\32\1\33"+
    "\2\30\1\34\4\30\1\35\1\36\1\37\1\40\1\41"+
    "\11\42\1\43\1\42\2\44\6\42\1\45\4\42\1\45"+
    "\15\42\13\46\2\47\6\46\1\50\4\46\1\50\15\46"+
    "\10\51\1\52\2\51\1\53\1\54\31\51\13\55\2\56"+
    "\31\55\2\57\1\60\1\61\5\57\1\60\3\57\1\60"+
    "\4\57\2\60\1\62\21\60\47\0\2\10\51\0\1\63"+
    "\50\0\1\64\54\0\1\65\40\0\2\30\5\0\2\30"+
    "\1\0\21\30\13\0\2\30\5\0\2\30\1\0\3\30"+
    "\1\66\15\30\13\0\2\30\5\0\2\30\1\0\10\30"+
    "\1\67\1\30\1\70\6\30\13\0\2\30\5\0\2\30"+
    "\1\0\10\30\1\71\2\30\1\72\5\30\13\0\2\30"+
    "\5\0\2\30\1\0\4\30\1\73\5\30\1\74\6\30"+
    "\13\0\2\30\5\0\2\30\1\0\15\30\1\75\3\30"+
    "\13\0\2\30\5\0\2\30\1\0\3\30\1\76\15\30"+
    "\13\0\2\30\5\0\2\30\1\0\17\30\1\77\1\30"+
    "\13\0\2\30\5\0\2\30\1\0\6\30\1\100\12\30"+
    "\13\0\2\30\5\0\2\30\1\0\6\30\1\101\12\30"+
    "\10\0\1\102\2\0\2\103\41\0\1\104\2\0\2\105"+
    "\44\0\1\53\1\106\34\0\1\107\42\0\6\63\1\110"+
    "\37\63\13\0\2\30\5\0\2\30\1\0\5\30\1\111"+
    "\13\30\13\0\2\30\5\0\2\30\1\0\16\30\1\112"+
    "\2\30\13\0\2\30\5\0\2\30\1\0\2\30\1\113"+
    "\16\30\13\0\2\30\5\0\2\30\1\0\13\30\1\114"+
    "\5\30\13\0\2\30\5\0\2\30\1\0\15\30\1\115"+
    "\3\30\13\0\2\30\5\0\2\30\1\0\17\30\1\116"+
    "\1\30\13\0\2\30\5\0\2\30\1\0\7\30\1\117"+
    "\3\30\1\120\5\30\13\0\2\30\5\0\2\30\1\0"+
    "\1\121\20\30\13\0\2\30\5\0\2\30\1\0\15\30"+
    "\1\122\3\30\13\0\2\30\5\0\2\30\1\0\3\30"+
    "\1\123\15\30\13\0\2\30\5\0\2\30\1\0\7\30"+
    "\1\124\11\30\13\0\2\103\44\0\2\105\31\0\6\63"+
    "\1\110\3\63\1\125\33\63\13\0\2\30\5\0\2\30"+
    "\1\0\7\30\1\126\11\30\13\0\2\30\5\0\2\30"+
    "\1\0\3\30\1\127\15\30\13\0\2\30\5\0\2\30"+
    "\1\0\1\130\20\30\13\0\2\30\5\0\2\30\1\0"+
    "\12\30\1\131\6\30\13\0\2\30\5\0\2\30\1\0"+
    "\5\30\1\132\13\30\13\0\2\30\5\0\2\30\1\0"+
    "\2\30\1\133\16\30\13\0\2\30\5\0\2\30\1\0"+
    "\7\30\1\134\11\30\13\0\2\30\5\0\2\30\1\0"+
    "\12\30\1\135\6\30\13\0\2\30\5\0\2\30\1\0"+
    "\10\30\1\136\10\30\13\0\2\30\5\0\2\30\1\0"+
    "\12\30\1\137\6\30\13\0\2\30\5\0\2\30\1\0"+
    "\17\30\1\140\1\30\13\0\2\30\5\0\2\30\1\0"+
    "\17\30\1\141\1\30\13\0\2\30\5\0\2\30\1\0"+
    "\15\30\1\142\3\30\13\0\2\30\5\0\2\30\1\0"+
    "\12\30\1\143\6\30\13\0\2\30\5\0\2\30\1\0"+
    "\3\30\1\144\15\30\13\0\2\30\5\0\2\30\1\0"+
    "\1\145\20\30\13\0\2\30\5\0\2\30\1\0\5\30"+
    "\1\146\13\30\13\0\2\30\5\0\2\30\1\0\11\30"+
    "\1\147\7\30";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2204];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\1\1\7\11\2\1\1\11\1\1\4\11"+
    "\12\1\3\11\1\1\2\11\1\1\1\11\1\1\7\11"+
    "\1\1\1\0\2\11\14\1\1\0\1\11\1\0\3\11"+
    "\1\0\14\1\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	private int intvalue=0;
	private String textvalue ="";
	private int fracvalue=0;
	private int fraclength=0;
	private int expvalue=0;
	private int expsign=1;
	private int startline =0;
	private int startcolumn =0;
	private String stringvalue="";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlexXScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case INT: {
              yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new IntConstToken(Token.INTCONST, textvalue, startline, startcolumn, intvalue);
            }  // fall though
            case 104: break;
            case FRACTION: {
              yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new FloatConstToken(Token.FLOATCONST, textvalue, startline, startcolumn,intvalue+fracvalue/Math.pow(10,fraclength));
            }  // fall though
            case 105: break;
            case EXPVZ: {
              yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new Token(Token.INVALID, textvalue, startline, startcolumn);
            }  // fall though
            case 106: break;
            case EXP: {
              yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new FloatConstToken(Token.FLOATCONST, textvalue, startline, startcolumn, (intvalue+fracvalue/Math.pow(10,fraclength))*Math.pow(10,expvalue*expsign));
            }  // fall though
            case 107: break;
            case STRING: {
              yybegin(YYINITIAL); return new Token(Token.INVALID, textvalue, startline, startcolumn);
            }  // fall though
            case 108: break;
            default:
              {
                return new Token(Token.EOF, yytext(), yyline+1, yycolumn+1);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(Token.INVALID,  yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 52: break;
          case 2:
            { /* eat whitespace */
            }
            // fall through
          case 53: break;
          case 3:
            { yybegin(STRING); textvalue="\""; stringvalue=""; startline=yyline+1; startcolumn=yycolumn+1;
            }
            // fall through
          case 54: break;
          case 4:
            { return new Token(Token.LBR, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 55: break;
          case 5:
            { return new Token(Token.RBR, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 56: break;
          case 6:
            { return new Token(Token.MULT, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 57: break;
          case 7:
            { return new Token(Token.PLUS, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 58: break;
          case 8:
            { return new Token(Token.MINUS, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 59: break;
          case 9:
            { return new Token(Token.DOT, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 60: break;
          case 10:
            { return new Token(Token.DIV, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 61: break;
          case 11:
            { return new IntConstToken(Token.INTCONST, yytext(), yyline+1, yycolumn+1, 0);
            }
            // fall through
          case 62: break;
          case 12:
            { yybegin(INT); textvalue=yytext(); startline=yyline+1; startcolumn=yycolumn+1;
						  intvalue=yytext().charAt(0)-'0'; fracvalue=0; fraclength=0; expvalue=0;
            }
            // fall through
          case 63: break;
          case 13:
            { return new Token(Token.COLON, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 64: break;
          case 14:
            { return new Token(Token.SEMICOLON, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 65: break;
          case 15:
            { return new Token(Token.LESS, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 66: break;
          case 16:
            { return new Token(Token.EQUALS, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 67: break;
          case 17:
            { return new Token(Token.MORE, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 68: break;
          case 18:
            { return new Token(Token.ID, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 69: break;
          case 19:
            { yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new IntConstToken(Token.INTCONST, textvalue, startline, startcolumn, intvalue);
            }
            // fall through
          case 70: break;
          case 20:
            { yybegin(FRACTION); 
							  textvalue+=yytext();
            }
            // fall through
          case 71: break;
          case 21:
            { intvalue = 10*intvalue + yytext().charAt(0)-'0'; 
							  textvalue+=yytext();
            }
            // fall through
          case 72: break;
          case 22:
            { yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new FloatConstToken(Token.FLOATCONST, textvalue, startline, startcolumn,intvalue+fracvalue/Math.pow(10,fraclength));
            }
            // fall through
          case 73: break;
          case 23:
            { fracvalue= 10*fracvalue+ yytext().charAt(0)-'0'; 
							  fraclength++;
							  textvalue+=yytext();
            }
            // fall through
          case 74: break;
          case 24:
            { yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new Token(Token.INVALID, textvalue, startline, startcolumn);
            }
            // fall through
          case 75: break;
          case 25:
            { yybegin(YYINITIAL);
							  return new FloatConstToken(Token.FLOATCONST, textvalue+yytext(), startline, startcolumn,intvalue+fracvalue/Math.pow(10,fraclength));
            }
            // fall through
          case 76: break;
          case 26:
            { yybegin(EXP); expvalue=yytext().charAt(0)-'0'; expsign=1; textvalue+=yytext();
            }
            // fall through
          case 77: break;
          case 27:
            { yybegin(YYINITIAL); 
					  		  yypushback(1); 
					  		  return new FloatConstToken(Token.FLOATCONST, textvalue, startline, startcolumn, (intvalue+fracvalue/Math.pow(10,fraclength))*Math.pow(10,expvalue*expsign));
            }
            // fall through
          case 78: break;
          case 28:
            { expvalue = 10* expvalue + yytext().charAt(0)-'0'; textvalue+=yytext();
            }
            // fall through
          case 79: break;
          case 29:
            { yybegin(YYINITIAL); return new Token(Token.INVALID, textvalue+yytext(), startline, startcolumn);
            }
            // fall through
          case 80: break;
          case 30:
            { textvalue+=yytext();  stringvalue+=yytext();
            }
            // fall through
          case 81: break;
          case 31:
            { yybegin(YYINITIAL); return new StringConstToken(Token.STRINGCONST, textvalue+"\"", startline, startcolumn, stringvalue);
            }
            // fall through
          case 82: break;
          case 32:
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 1);
            { yybegin(INT); textvalue=yytext(); startline=yyline+1; startcolumn=yycolumn+1;
						  intvalue=yytext().charAt(0)-'0'; fracvalue=0; fraclength=0; expvalue=0;
            }
            // fall through
          case 83: break;
          case 33:
            { return new Token(Token.ASSIGN, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 84: break;
          case 34:
            { return new Token(Token.IF, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 85: break;
          case 35:
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 1);
            { yybegin(EXPVZ);  textvalue += yytext();
            }
            // fall through
          case 86: break;
          case 36:
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 1);
            { yybegin(EXPVZ); 
							  textvalue+=yytext();
            }
            // fall through
          case 87: break;
          case 37:
            { yybegin(EXP); expvalue=yytext().charAt(1)-'0'; expsign=-1; textvalue+=yytext();
            }
            // fall through
          case 88: break;
          case 38:
            { textvalue+="\\\""; stringvalue+="\"";
            }
            // fall through
          case 89: break;
          case 39:
            { return new Token(Token.END, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 90: break;
          case 40:
            { return new Token(Token.FOR, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 91: break;
          case 41:
            { return new Token(Token.INT, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 92: break;
          case 42:
            { /* eat comments */
            }
            // fall through
          case 93: break;
          case 43:
            { return new Token(Token.ELSE, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 94: break;
          case 44:
            { return new Token(Token.READ, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 95: break;
          case 45:
            { return new Token(Token.THEN, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 96: break;
          case 46:
            { return new Token(Token.BEGIN, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 97: break;
          case 47:
            { return new Token(Token.FLOAT, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 98: break;
          case 48:
            { return new Token(Token.PRINT, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 99: break;
          case 49:
            { return new Token(Token.WHILE, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 100: break;
          case 50:
            { return new Token(Token.STRING, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 101: break;
          case 51:
            { return new Token(Token.PROGRAM, yytext(), yyline+1, yycolumn+1);
            }
            // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
